import type { TranslationKey } from "../../../shared/i18n";
import type { SettingsCategoryKey } from "../components/SettingsCategoryNav";

export interface SettingsCatalogEntry {
  category: SettingsCategoryKey;
  itemId: string;
  labelKey: TranslationKey;
  descriptionKey?: TranslationKey;
  keywords?: ReadonlyArray<string>;
}

export const SETTINGS_CATALOG: ReadonlyArray<SettingsCatalogEntry> = [
  // ── general ──────────────────────────────────────────
  { category: "general", itemId: "useOnlineService", labelKey: "settings.general.useOnlineService", descriptionKey: "settings.general.useOnlineService.desc", keywords: ["online", "service", "在线服务"] },
  { category: "general", itemId: "closeAppMethod", labelKey: "settings.general.closeAppMethod", descriptionKey: "settings.general.closeAppMethod.desc", keywords: ["close", "exit", "tray", "关闭", "退出"] },
  { category: "general", itemId: "showCloseAppTip", labelKey: "settings.general.showCloseAppTip", descriptionKey: "settings.general.showCloseAppTip.desc", keywords: ["close", "tip", "confirm", "提醒"] },
  { category: "general", itemId: "showTaskbarProgress", labelKey: "settings.general.showTaskbarProgress", descriptionKey: "settings.general.showTaskbarProgress.desc", keywords: ["taskbar", "progress", "任务栏", "进度"] },
  { category: "general", itemId: "checkUpdateOnStart", labelKey: "settings.general.checkUpdateOnStart", descriptionKey: "settings.general.checkUpdateOnStart.desc", keywords: ["update", "startup", "更新"] },
  { category: "general", itemId: "updateChannel", labelKey: "settings.general.updateChannel", descriptionKey: "settings.general.updateChannel.desc", keywords: ["update", "channel", "nightly", "更新通道"] },
  { category: "general", itemId: "showSearchHistory", labelKey: "settings.general.showSearchHistory", descriptionKey: "settings.general.showSearchHistory.desc", keywords: ["search", "history", "搜索历史"] },
  { category: "general", itemId: "showHotSearch", labelKey: "settings.general.showHotSearch", descriptionKey: "settings.general.showHotSearch.desc", keywords: ["search", "hot", "热搜"] },
  { category: "general", itemId: "enableSearchKeyword", labelKey: "settings.general.enableSearchKeyword", descriptionKey: "settings.general.enableSearchKeyword.desc", keywords: ["search", "keyword", "suggestion", "搜索建议"] },
  { category: "general", itemId: "searchInputBehavior", labelKey: "settings.general.searchInputBehavior", descriptionKey: "settings.general.searchInputBehavior.desc", keywords: ["search", "input", "behavior", "搜索框"] },
  { category: "general", itemId: "shareUrlFormat", labelKey: "settings.general.shareUrlFormat", descriptionKey: "settings.general.shareUrlFormat.desc", keywords: ["share", "url", "link", "分享"] },

  // ── appearance ───────────────────────────────────────
  { category: "appearance", itemId: "themeMode", labelKey: "settings.appearance.themeMode", keywords: ["theme", "dark", "light", "主题"] },
  { category: "appearance", itemId: "themeConfig", labelKey: "settings.appearance.themeConfig", descriptionKey: "settings.appearance.themeConfig.desc", keywords: ["theme", "color", "主题", "配色"] },
  { category: "appearance", itemId: "themeGlobalColor", labelKey: "settings.appearance.themeGlobalColor", descriptionKey: "settings.appearance.themeGlobalColor.desc", keywords: ["theme", "global", "accent", "全局着色"] },
  { category: "appearance", itemId: "customAccentColor", labelKey: "settings.appearance.customAccentColor", descriptionKey: "settings.appearance.customAccentColor.desc", keywords: ["theme", "color", "accent", "主题色"] },
  { category: "appearance", itemId: "themeFollowCover", labelKey: "settings.appearance.themeFollowCover", descriptionKey: "settings.appearance.themeFollowCover.desc", keywords: ["cover", "accent", "dynamic", "动态取色"] },
  { category: "appearance", itemId: "fontConfig", labelKey: "settings.appearance.fontConfig", descriptionKey: "settings.appearance.fontConfig.desc", keywords: ["font", "字体"] },
  { category: "appearance", itemId: "globalFont", labelKey: "settings.appearance.globalFont", descriptionKey: "settings.appearance.globalFont.desc", keywords: ["font", "字体"] },
  { category: "appearance", itemId: "customFontFamily", labelKey: "settings.appearance.customFontFamily", descriptionKey: "settings.appearance.customFontFamily.desc", keywords: ["font", "family", "字体栈"] },
  { category: "appearance", itemId: "customCode", labelKey: "settings.appearance.customCode", descriptionKey: "settings.appearance.customCode.desc", keywords: ["css", "js", "custom", "code", "自定义"] },
  { category: "appearance", itemId: "customCss", labelKey: "settings.appearance.customCss", descriptionKey: "settings.appearance.customCss.desc", keywords: ["css", "style", "样式"] },
  { category: "appearance", itemId: "customJs", labelKey: "settings.appearance.customJs", descriptionKey: "settings.appearance.customJs.desc", keywords: ["javascript", "js", "script", "脚本"] },
  { category: "appearance", itemId: "routeAnimation", labelKey: "settings.appearance.routeAnimation", keywords: ["animation", "transition", "动画"] },
  { category: "appearance", itemId: "bgEnabled", labelKey: "settings.general.background.enabled", keywords: ["background", "wallpaper", "背景"] },
  { category: "appearance", itemId: "bgBlur", labelKey: "settings.general.background.blur", keywords: ["blur", "模糊"] },
  { category: "appearance", itemId: "bgMask", labelKey: "settings.general.background.mask", keywords: ["mask", "opacity", "遮罩"] },
  { category: "appearance", itemId: "customChrome", labelKey: "settings.general.window.customChrome", keywords: ["window", "frame", "边框", "标题栏"] },
  { category: "appearance", itemId: "sidebarHiddenItems", labelKey: "settings.appearance.sidebarManager", descriptionKey: "settings.appearance.sidebarManager.desc", keywords: ["sidebar", "menu", "侧边栏"] },
  { category: "appearance", itemId: "homeSections", labelKey: "settings.general.homeSections.title", descriptionKey: "settings.general.homeSections.desc", keywords: ["home", "section", "板块"] },
  { category: "appearance", itemId: "playlistPageElements", labelKey: "settings.appearance.playlistPageManager", descriptionKey: "settings.appearance.playlistPageManager.desc", keywords: ["playlist", "detail", "歌单"] },
  { category: "appearance", itemId: "fullPlayerElements", labelKey: "settings.appearance.fullPlayerManager", descriptionKey: "settings.appearance.fullPlayerManager.desc", keywords: ["full", "player", "fullscreen", "全屏播放器"] },
  { category: "appearance", itemId: "contextMenuOptions", labelKey: "settings.appearance.contextMenuManager", descriptionKey: "settings.appearance.contextMenuManager.desc", keywords: ["context", "menu", "right click", "右键菜单"] },
  { category: "appearance", itemId: "sidebarHiddenItems.recommend", labelKey: "settings.appearance.sidebar.recommend", keywords: ["sidebar", "recommend", "hide", "侧边栏", "推荐"] },
  { category: "appearance", itemId: "sidebarHiddenItems.discover", labelKey: "settings.appearance.sidebar.discover", keywords: ["sidebar", "discover", "hide", "侧边栏", "发现"] },
  { category: "appearance", itemId: "sidebarHiddenItems.personalFm", labelKey: "settings.appearance.sidebar.personalFm", keywords: ["sidebar", "fm", "hide", "私人漫游"] },
  { category: "appearance", itemId: "sidebarHiddenItems.radio", labelKey: "settings.appearance.sidebar.radio", keywords: ["sidebar", "radio", "hide", "播客"] },
  { category: "appearance", itemId: "sidebarHiddenItems.likedSongs", labelKey: "settings.appearance.sidebar.likedSongs", keywords: ["sidebar", "liked", "favorite", "我喜欢"] },
  { category: "appearance", itemId: "sidebarHiddenItems.liked", labelKey: "settings.appearance.sidebar.liked", keywords: ["sidebar", "liked", "favorite", "收藏"] },
  { category: "appearance", itemId: "sidebarHiddenItems.cloud", labelKey: "settings.appearance.sidebar.cloud", keywords: ["sidebar", "cloud", "云盘"] },
  { category: "appearance", itemId: "sidebarHiddenItems.download", labelKey: "settings.appearance.sidebar.download", keywords: ["sidebar", "download", "下载"] },
  { category: "appearance", itemId: "sidebarHiddenItems.streaming", labelKey: "settings.appearance.sidebar.streaming", keywords: ["sidebar", "streaming", "流媒体"] },
  { category: "appearance", itemId: "sidebarHiddenItems.library", labelKey: "settings.appearance.sidebar.library", keywords: ["sidebar", "library", "本地"] },
  { category: "appearance", itemId: "sidebarHiddenItems.recent", labelKey: "settings.appearance.sidebar.recent", keywords: ["sidebar", "history", "recent", "最近"] },
  { category: "appearance", itemId: "sidebarHiddenItems.createdPlaylists", labelKey: "settings.appearance.sidebar.createdPlaylists", keywords: ["sidebar", "playlist", "created", "创建歌单"] },
  { category: "appearance", itemId: "sidebarHiddenItems.collectedPlaylists", labelKey: "settings.appearance.sidebar.collectedPlaylists", keywords: ["sidebar", "playlist", "collected", "收藏歌单"] },
  { category: "appearance", itemId: "sidebarHiddenItems.heartbeatMode", labelKey: "settings.appearance.sidebar.heartbeatMode", keywords: ["sidebar", "heartbeat", "心动模式"] },
  { category: "appearance", itemId: "showHomeGreeting", labelKey: "settings.general.showHomeGreeting", descriptionKey: "settings.general.showHomeGreeting.desc", keywords: ["home", "greeting", "问好", "问候"] },
  { category: "appearance", itemId: "menuShowCover", labelKey: "settings.appearance.menuShowCover", descriptionKey: "settings.appearance.menuShowCover.desc", keywords: ["sidebar", "cover", "playlist", "封面"] },
  { category: "appearance", itemId: "playlistPageElements.tags", labelKey: "settings.appearance.playlistPage.tags", keywords: ["playlist", "detail", "tag", "歌单", "标签"] },
  { category: "appearance", itemId: "playlistPageElements.creator", labelKey: "settings.appearance.playlistPage.creator", keywords: ["playlist", "detail", "creator", "创建者"] },
  { category: "appearance", itemId: "playlistPageElements.time", labelKey: "settings.appearance.playlistPage.time", keywords: ["playlist", "detail", "time", "count", "时间"] },
  { category: "appearance", itemId: "playlistPageElements.description", labelKey: "settings.appearance.playlistPage.description", keywords: ["playlist", "detail", "description", "描述"] },
  { category: "appearance", itemId: "contextMenuOptions.play", labelKey: "settings.appearance.contextMenu.play", keywords: ["context", "menu", "play", "右键", "播放"] },
  { category: "appearance", itemId: "contextMenuOptions.playNext", labelKey: "settings.appearance.contextMenu.playNext", keywords: ["context", "menu", "next", "queue", "下一首"] },
  { category: "appearance", itemId: "contextMenuOptions.addToPlaylist", labelKey: "settings.appearance.contextMenu.addToPlaylist", keywords: ["context", "menu", "playlist", "歌单"] },
  { category: "appearance", itemId: "contextMenuOptions.mv", labelKey: "settings.appearance.contextMenu.mv", keywords: ["context", "menu", "mv", "video", "MV", "视频"] },
  { category: "appearance", itemId: "contextMenuOptions.dislike", labelKey: "settings.appearance.contextMenu.dislike", keywords: ["context", "menu", "dislike", "not interested", "不感兴趣"] },
  { category: "appearance", itemId: "contextMenuOptions.more", labelKey: "settings.appearance.contextMenu.more", keywords: ["context", "menu", "more", "right click", "更多操作"] },
  { category: "appearance", itemId: "contextMenuOptions.cloudImport", labelKey: "settings.appearance.contextMenu.cloudImport", keywords: ["context", "menu", "cloud", "import", "云盘", "导入"] },
  { category: "appearance", itemId: "contextMenuOptions.search", labelKey: "settings.appearance.contextMenu.search", keywords: ["context", "menu", "search", "right click", "搜索"] },
  { category: "appearance", itemId: "contextMenuOptions.copyName", labelKey: "settings.appearance.contextMenu.copyName", keywords: ["context", "menu", "copy", "name", "title", "复制", "歌曲名称"] },
  { category: "appearance", itemId: "contextMenuOptions.wiki", labelKey: "settings.appearance.contextMenu.wiki", keywords: ["context", "menu", "wiki", "百科", "歌曲百科"] },
  { category: "appearance", itemId: "contextMenuOptions.download", labelKey: "settings.appearance.contextMenu.download", keywords: ["context", "menu", "download", "下载"] },
  { category: "appearance", itemId: "contextMenuOptions.openFolder", labelKey: "settings.appearance.contextMenu.openFolder", keywords: ["context", "menu", "folder", "local", "右键", "文件夹"] },
  { category: "appearance", itemId: "contextMenuOptions.deleteFromPlaylist", labelKey: "settings.appearance.contextMenu.deleteFromPlaylist", keywords: ["context", "menu", "playlist", "delete", "移除", "歌单"] },
  { category: "appearance", itemId: "contextMenuOptions.deleteFromCloud", labelKey: "settings.appearance.contextMenu.deleteFromCloud", keywords: ["context", "menu", "cloud", "delete", "云盘", "删除"] },
  { category: "appearance", itemId: "contextMenuOptions.cloudMatch", labelKey: "settings.appearance.contextMenu.cloudMatch", keywords: ["context", "menu", "cloud", "match", "云盘", "纠正"] },
  { category: "appearance", itemId: "contextMenuOptions.deleteFromLibrary", labelKey: "settings.appearance.contextMenu.deleteFromLibrary", keywords: ["context", "menu", "library", "delete", "本地库", "删除"] },
  { category: "appearance", itemId: "contextMenuOptions.musicTagEditor", labelKey: "settings.appearance.contextMenu.musicTagEditor", keywords: ["context", "menu", "tag", "editor", "标签", "编辑"] },
  { category: "appearance", itemId: "coverManager", labelKey: "settings.appearance.coverManager", descriptionKey: "settings.appearance.coverManager.desc", keywords: ["cover", "display", "封面"] },
  { category: "appearance", itemId: "hiddenCovers.home", labelKey: "settings.appearance.cover.home", keywords: ["cover", "home", "recommend", "封面", "为我推荐"] },
  { category: "appearance", itemId: "hiddenCovers.playlist", labelKey: "settings.appearance.cover.playlist", keywords: ["cover", "playlist", "封面", "歌单"] },
  { category: "appearance", itemId: "hiddenCovers.toplist", labelKey: "settings.appearance.cover.toplist", keywords: ["cover", "toplist", "rank", "封面", "排行榜"] },
  { category: "appearance", itemId: "hiddenCovers.artist", labelKey: "settings.appearance.cover.artist", keywords: ["cover", "artist", "封面", "歌手"] },
  { category: "appearance", itemId: "hiddenCovers.new", labelKey: "settings.appearance.cover.new", keywords: ["cover", "new", "music", "封面", "最新音乐"] },
  { category: "appearance", itemId: "hiddenCovers.personalFM", labelKey: "settings.appearance.cover.personalFM", keywords: ["cover", "fm", "radio", "封面", "私人FM"] },
  { category: "appearance", itemId: "hiddenCovers.player", labelKey: "settings.appearance.cover.player", keywords: ["cover", "player", "封面", "播放器"] },
  { category: "appearance", itemId: "hiddenCovers.list", labelKey: "settings.appearance.cover.list", keywords: ["cover", "list", "detail", "封面", "歌曲列表"] },
  { category: "appearance", itemId: "hiddenCovers.artistDetail", labelKey: "settings.appearance.cover.artistDetail", keywords: ["cover", "artist", "detail", "封面", "歌手详情"] },
  { category: "appearance", itemId: "hiddenCovers.radio", labelKey: "settings.appearance.cover.radio", keywords: ["cover", "radio", "podcast", "封面", "电台"] },
  { category: "appearance", itemId: "hiddenCovers.album", labelKey: "settings.appearance.cover.album", keywords: ["cover", "album", "封面", "专辑"] },
  { category: "appearance", itemId: "hiddenCovers.like", labelKey: "settings.appearance.cover.like", keywords: ["cover", "favorite", "like", "封面", "收藏"] },
  { category: "appearance", itemId: "hiddenCovers.video", labelKey: "settings.appearance.cover.video", keywords: ["cover", "video", "封面", "视频"] },
  { category: "appearance", itemId: "hiddenCovers.videoDetail", labelKey: "settings.appearance.cover.videoDetail", keywords: ["cover", "video", "detail", "封面", "视频详情"] },
  { category: "appearance", itemId: "fullPlayerLayout", labelKey: "settings.general.fullPlayer.layout", keywords: ["full", "lyrics", "全屏"] },
  { category: "appearance", itemId: "fullPlayerAutoFocusLyrics", labelKey: "settings.general.fullPlayer.autoFocusLyrics", keywords: ["focus", "lyrics", "歌词"] },
  { category: "appearance", itemId: "playerType", labelKey: "settings.appearance.playerType", descriptionKey: "settings.appearance.playerType.desc", keywords: ["cover", "record", "fullscreen", "封面", "唱片", "播放器样式"] },
  { category: "appearance", itemId: "playerStyleRatio", labelKey: "settings.appearance.playerStyleRatio", descriptionKey: "settings.appearance.playerStyleRatio.desc", keywords: ["ratio", "cover", "lyrics", "占比"] },
  { category: "appearance", itemId: "playerFullscreenGradient", labelKey: "settings.appearance.playerFullscreenGradient", descriptionKey: "settings.appearance.playerFullscreenGradient.desc", keywords: ["gradient", "fullscreen", "cover", "渐变"] },
  { category: "appearance", itemId: "fullPlayerCommentMode", labelKey: "settings.general.fullPlayer.commentMode", keywords: ["comment", "layout", "评论"] },
  { category: "appearance", itemId: "playerBackgroundType", labelKey: "settings.appearance.playerBackgroundType", descriptionKey: "settings.appearance.playerBackgroundType.desc", keywords: ["background", "blur", "fluid", "背景", "流体"] },
  { category: "appearance", itemId: "playerBackgroundFps", labelKey: "settings.appearance.playerBackgroundFps", descriptionKey: "settings.appearance.playerBackgroundFps.desc", keywords: ["fps", "frame", "background", "帧率", "背景"] },
  { category: "appearance", itemId: "playerBackgroundFlowSpeed", labelKey: "settings.appearance.playerBackgroundFlowSpeed", descriptionKey: "settings.appearance.playerBackgroundFlowSpeed.desc", keywords: ["speed", "flow", "背景", "速度"] },
  { category: "appearance", itemId: "playerBackgroundRenderScale", labelKey: "settings.appearance.playerBackgroundRenderScale", descriptionKey: "settings.appearance.playerBackgroundRenderScale.desc", keywords: ["render", "scale", "background", "渲染", "缩放"] },
  { category: "appearance", itemId: "playerBackgroundPause", labelKey: "settings.appearance.playerBackgroundPause", descriptionKey: "settings.appearance.playerBackgroundPause.desc", keywords: ["pause", "background", "暂停"] },
  { category: "appearance", itemId: "playerBackgroundLowFreqVolume", labelKey: "settings.appearance.playerBackgroundLowFreqVolume", descriptionKey: "settings.appearance.playerBackgroundLowFreqVolume.desc", keywords: ["bass", "pulse", "low", "低频", "跳动"] },
  { category: "appearance", itemId: "playerExpandAnimation", labelKey: "settings.appearance.playerExpandAnimation", descriptionKey: "settings.appearance.playerExpandAnimation.desc", keywords: ["expand", "animation", "full player", "展开", "动画"] },
  { category: "appearance", itemId: "dynamicCover", labelKey: "settings.appearance.dynamicCover", descriptionKey: "settings.appearance.dynamicCover.desc", keywords: ["dynamic", "cover", "animated", "封面", "动态封面"] },
  { category: "appearance", itemId: "playerFollowCoverColor", labelKey: "settings.appearance.playerFollowCoverColor", descriptionKey: "settings.appearance.playerFollowCoverColor.desc", keywords: ["accent", "cover", "color", "theme", "封面", "主色"] },
  { category: "appearance", itemId: "autoHidePlayerMeta", labelKey: "settings.appearance.autoHidePlayerMeta", descriptionKey: "settings.appearance.autoHidePlayerMeta.desc", keywords: ["auto", "hide", "controls", "自动隐藏"] },
  { category: "appearance", itemId: "showPlayMeta", labelKey: "settings.appearance.showPlayMeta", descriptionKey: "settings.appearance.showPlayMeta.desc", keywords: ["player", "meta", "status", "播放状态"] },
  { category: "appearance", itemId: "countDownShow", labelKey: "settings.appearance.countDownShow", descriptionKey: "settings.appearance.countDownShow.desc", keywords: ["countdown", "intro", "倒计时"] },
  { category: "appearance", itemId: "showSpectrums", labelKey: "settings.appearance.showSpectrums", descriptionKey: "settings.appearance.showSpectrums.desc", keywords: ["spectrum", "visualizer", "频谱"] },
  { category: "appearance", itemId: "showPlaylistCount", labelKey: "settings.appearance.showPlaylistCount", descriptionKey: "settings.appearance.showPlaylistCount.desc", keywords: ["queue", "count", "badge", "队列"] },
  { category: "appearance", itemId: "barLyricShow", labelKey: "settings.appearance.barLyricShow", descriptionKey: "settings.appearance.barLyricShow.desc", keywords: ["bar", "lyric", "歌词"] },
  { category: "appearance", itemId: "showPlayerQuality", labelKey: "settings.appearance.showPlayerQuality", descriptionKey: "settings.appearance.showPlayerQuality.desc", keywords: ["quality", "sample", "音质"] },
  { category: "appearance", itemId: "timeFormat", labelKey: "settings.appearance.timeFormat", descriptionKey: "settings.appearance.timeFormat.desc", keywords: ["time", "remaining", "duration", "时间"] },
  { category: "appearance", itemId: "showSongAlbum", labelKey: "settings.appearance.showSongAlbum", descriptionKey: "settings.appearance.showSongAlbum.desc", keywords: ["song", "album", "list", "专辑"] },
  { category: "appearance", itemId: "showSongArtist", labelKey: "settings.appearance.showSongArtist", descriptionKey: "settings.appearance.showSongArtist.desc", keywords: ["song", "artist", "list", "歌手"] },
  { category: "appearance", itemId: "showSongDuration", labelKey: "settings.appearance.showSongDuration", descriptionKey: "settings.appearance.showSongDuration.desc", keywords: ["song", "duration", "list", "时长"] },
  { category: "appearance", itemId: "showSongOperations", labelKey: "settings.appearance.showSongOperations", descriptionKey: "settings.appearance.showSongOperations.desc", keywords: ["song", "action", "operation", "操作"] },
  { category: "appearance", itemId: "showSongQuality", labelKey: "settings.appearance.showSongQuality", descriptionKey: "settings.appearance.showSongQuality.desc", keywords: ["song", "quality", "list", "音质"] },
  { category: "appearance", itemId: "showSongPrivilegeTag", labelKey: "settings.appearance.showSongPrivilegeTag", descriptionKey: "settings.appearance.showSongPrivilegeTag.desc", keywords: ["song", "tag", "vip", "特权"] },
  { category: "appearance", itemId: "showSongExplicitTag", labelKey: "settings.appearance.showSongExplicitTag", descriptionKey: "settings.appearance.showSongExplicitTag.desc", keywords: ["song", "explicit", "tag", "脏标"] },
  { category: "appearance", itemId: "showSongOriginalTag", labelKey: "settings.appearance.showSongOriginalTag", descriptionKey: "settings.appearance.showSongOriginalTag.desc", keywords: ["song", "original", "tag", "原唱"] },
  { category: "appearance", itemId: "hideBracketedContent", labelKey: "settings.appearance.hideBracketedContent", descriptionKey: "settings.appearance.hideBracketedContent.desc", keywords: ["song", "bracket", "alias", "括号"] },
  { category: "appearance", itemId: "fullPlayerShowLike", labelKey: "settings.appearance.fullPlayerShowLike", keywords: ["favorite", "heart", "喜欢"] },
  { category: "appearance", itemId: "fullPlayerShowAddToPlaylist", labelKey: "settings.appearance.fullPlayerShowAddToPlaylist", keywords: ["playlist", "add", "歌单"] },
  { category: "appearance", itemId: "fullPlayerShowDownload", labelKey: "settings.appearance.fullPlayerShowDownload", keywords: ["download", "下载"] },
  { category: "appearance", itemId: "fullPlayerShowComments", labelKey: "settings.appearance.fullPlayerShowComments", keywords: ["comment", "评论"] },
  { category: "appearance", itemId: "fullPlayerShowCommentCount", labelKey: "settings.appearance.fullPlayerShowCommentCount", keywords: ["comment", "count", "badge", "评论"] },
  { category: "appearance", itemId: "fullPlayerShowCopyLyric", labelKey: "settings.appearance.fullPlayerShowCopyLyric", keywords: ["copy", "lyric", "clipboard", "复制歌词"] },
  { category: "appearance", itemId: "fullPlayerShowDesktopLyric", labelKey: "settings.appearance.fullPlayerShowDesktopLyric", keywords: ["desktop", "lyric", "桌面歌词"] },
  { category: "appearance", itemId: "fullPlayerShowLyricOffset", labelKey: "settings.appearance.fullPlayerShowLyricOffset", keywords: ["lyric", "offset", "adjust", "歌词调整"] },
  { category: "appearance", itemId: "fullPlayerShowLyricSettings", labelKey: "settings.appearance.fullPlayerShowLyricSettings", keywords: ["lyric", "settings", "歌词设置"] },
  { category: "appearance", itemId: "fullPlayerShowMoreSettings", labelKey: "settings.appearance.fullPlayerShowMoreSettings", keywords: ["more", "settings", "更多"] },

  // ── playback ─────────────────────────────────────────
  { category: "playback", itemId: "autoPlay", labelKey: "settings.playback.autoPlay", descriptionKey: "settings.playback.autoPlay.desc", keywords: ["auto", "play", "启动"] },
  { category: "playback", itemId: "useNextPrefetch", labelKey: "settings.playback.useNextPrefetch", descriptionKey: "settings.playback.useNextPrefetch.desc", keywords: ["preload", "prefetch", "next", "预载", "下一首"] },
  { category: "playback", itemId: "volumeFade", labelKey: "settings.playback.volumeFade", descriptionKey: "settings.playback.volumeFade.desc", keywords: ["fade", "volume", "渐入"] },
  { category: "playback", itemId: "volumeFadeTime", labelKey: "settings.playback.volumeFadeTime", keywords: ["fade", "duration", "时长"] },
  { category: "playback", itemId: "memoryLastSeek", labelKey: "settings.playback.memoryLastSeek", descriptionKey: "settings.playback.memoryLastSeek.desc", keywords: ["memory", "seek", "记忆"] },
  { category: "playback", itemId: "progressTooltipShow", labelKey: "settings.playback.progressTooltipShow", descriptionKey: "settings.playback.progressTooltipShow.desc", keywords: ["progress", "tooltip", "进度条"] },
  { category: "playback", itemId: "progressLyricShow", labelKey: "settings.playback.progressLyricShow", descriptionKey: "settings.playback.progressLyricShow.desc", keywords: ["progress", "lyric", "歌词"] },
  { category: "playback", itemId: "progressAdjustLyric", labelKey: "settings.playback.progressAdjustLyric", descriptionKey: "settings.playback.progressAdjustLyric.desc", keywords: ["progress", "snap", "seek", "吸附"] },
  { category: "playback", itemId: "ncmSongLevel", labelKey: "settings.ncm.songLevel", descriptionKey: "settings.ncm.songLevel.desc", keywords: ["ncm", "quality", "音质", "网易云"] },

  // ── lyrics ───────────────────────────────────────────
  { category: "lyrics", itemId: "lyricFontSize", labelKey: "settings.lyric.fontSize", keywords: ["font", "size", "字体"] },
  { category: "lyrics", itemId: "lyricFontWeight", labelKey: "settings.lyric.fontWeight", descriptionKey: "settings.lyric.fontWeight.desc", keywords: ["font", "weight", "字重"] },
  { category: "lyrics", itemId: "lyricTranslationFontSize", labelKey: "settings.lyric.translationFontSize", descriptionKey: "settings.lyric.translationFontSize.desc", keywords: ["translation", "font", "翻译"] },
  { category: "lyrics", itemId: "lyricRomanizationFontSize", labelKey: "settings.lyric.romanizationFontSize", descriptionKey: "settings.lyric.romanizationFontSize.desc", keywords: ["roman", "romaji", "font", "音译"] },
  { category: "lyrics", itemId: "showLyricTranslation", labelKey: "settings.lyric.showTranslation", descriptionKey: "settings.lyric.showTranslation.desc", keywords: ["translation", "翻译"] },
  { category: "lyrics", itemId: "showLyricRomanization", labelKey: "settings.lyric.showRomanization", descriptionKey: "settings.lyric.showRomanization.desc", keywords: ["roman", "romaji", "罗马音"] },
  { category: "lyrics", itemId: "swapLyricTranslationRomanization", labelKey: "settings.lyric.swapTranslationRomanization", descriptionKey: "settings.lyric.swapTranslationRomanization.desc", keywords: ["swap", "translation", "roman", "翻译", "音译"] },
  { category: "lyrics", itemId: "showWordLyrics", labelKey: "settings.lyric.showWordLyrics", descriptionKey: "settings.lyric.showWordLyrics.desc", keywords: ["word", "yrc", "逐字"] },
  { category: "lyrics", itemId: "lyricsBlur", labelKey: "settings.lyric.blur", descriptionKey: "settings.lyric.blur.desc", keywords: ["blur", "depth", "虚化"] },
  { category: "lyrics", itemId: "lyricsScrollOffset", labelKey: "settings.lyric.scrollOffset", descriptionKey: "settings.lyric.scrollOffset.desc", keywords: ["scroll", "offset", "position", "滚动"] },
  { category: "lyrics", itemId: "lyricsPosition", labelKey: "settings.lyric.position", descriptionKey: "settings.lyric.position.desc", keywords: ["align", "position", "对齐"] },
  { category: "lyrics", itemId: "lyricHorizontalOffset", labelKey: "settings.lyric.horizontalOffset", descriptionKey: "settings.lyric.horizontalOffset.desc", keywords: ["offset", "margin", "边距"] },
  { category: "lyrics", itemId: "lyricAlignRight", labelKey: "settings.lyric.alignRight", descriptionKey: "settings.lyric.alignRight.desc", keywords: ["right", "align", "靠右"] },
  { category: "lyrics", itemId: "lyricsBlendMode", labelKey: "settings.lyric.blendMode", descriptionKey: "settings.lyric.blendMode.desc", keywords: ["blend", "screen", "mix", "混合"] },

  // ── audio-engine ─────────────────────────────────────
  { category: "audio-engine", itemId: "device", labelKey: "settings.device.label", keywords: ["device", "output", "设备"] },
  { category: "audio-engine", itemId: "exclusive", labelKey: "settings.exclusiveMode", keywords: ["exclusive", "wasapi", "独占"] },
  { category: "audio-engine", itemId: "volume", labelKey: "settings.volume", keywords: ["volume", "音量"] },
  { category: "audio-engine", itemId: "upsampling", labelKey: "settings.upsampling", keywords: ["upsample", "samplerate", "上采样"] },
  { category: "audio-engine", itemId: "eqType", labelKey: "settings.eq.profile", keywords: ["eq", "iir", "fir", "均衡"] },
  { category: "audio-engine", itemId: "firTaps", labelKey: "settings.eq.firTaps", keywords: ["fir", "taps"] },
  { category: "audio-engine", itemId: "eqBands", labelKey: "settings.eq.bandsTitle", keywords: ["eq", "bands", "频段"] },
  { category: "audio-engine", itemId: "outputBits", labelKey: "settings.outputBits", keywords: ["bits", "位深"] },
  { category: "audio-engine", itemId: "noiseShaper", labelKey: "settings.noiseShaper", keywords: ["dither", "noise", "shaper"] },
  { category: "audio-engine", itemId: "dither", labelKey: "settings.dither", keywords: ["dither", "抖动"] },
  { category: "audio-engine", itemId: "loudnessEnabled", labelKey: "settings.loudnessEnabled", keywords: ["loudness", "lufs", "响度"] },
  { category: "audio-engine", itemId: "loudnessMode", labelKey: "settings.loudnessMode", keywords: ["loudness", "track", "album"] },
  { category: "audio-engine", itemId: "targetLufs", labelKey: "settings.targetLufs", keywords: ["lufs", "target", "目标"] },
  { category: "audio-engine", itemId: "preamp", labelKey: "settings.preamp", keywords: ["preamp", "前级"] },
  { category: "audio-engine", itemId: "resampleQuality", labelKey: "settings.resampleQuality", keywords: ["resample", "quality", "重采样"] },
  { category: "audio-engine", itemId: "saturationEnabled", labelKey: "settings.saturation.enabled", keywords: ["saturation", "饱和"] },
  { category: "audio-engine", itemId: "saturationDrive", labelKey: "settings.saturation.drive" },
  { category: "audio-engine", itemId: "saturationMix", labelKey: "settings.saturation.mix" },
  { category: "audio-engine", itemId: "crossfeedEnabled", labelKey: "settings.crossfeed.enabled", keywords: ["crossfeed", "串扰"] },
  { category: "audio-engine", itemId: "crossfeedMix", labelKey: "settings.crossfeed.mix" },
  { category: "audio-engine", itemId: "dynamicLoudnessEnabled", labelKey: "settings.dynamicLoudness.enabled", keywords: ["dynamic", "loudness"] },
  { category: "audio-engine", itemId: "dynamicLoudnessStrength", labelKey: "settings.dynamicLoudness.strength" },
  { category: "audio-engine", itemId: "useCache", labelKey: "settings.useCache", keywords: ["cache", "缓存"] },
  { category: "audio-engine", itemId: "preemptiveResample", labelKey: "settings.preemptiveResample", keywords: ["preemptive", "resample", "预先"] },

  // ── local ────────────────────────────────────────────
  { category: "local", itemId: "localMusicDirectory", labelKey: "settings.local.localMusicDirectory", descriptionKey: "settings.local.localMusicDirectory.desc", keywords: ["local", "music", "folder", "directory", "本地", "音乐", "目录"] },
  { category: "local", itemId: "localFolderDisplayMode", labelKey: "settings.local.localFolderDisplayMode", keywords: ["local", "folder", "display", "tree", "flat", "本地", "文件夹", "显示", "树状"] },
  { category: "local", itemId: "showLocalCover", labelKey: "settings.local.showLocalCover", keywords: ["local", "cover", "art", "本地", "封面"] },
  { category: "local", itemId: "showDefaultLocalPath", labelKey: "settings.local.showDefaultLocalPath", keywords: ["local", "default", "path", "本地", "默认", "路径"] },
  { category: "local", itemId: "localLyricDirectories", labelKey: "settings.local.localLyricDirectories", descriptionKey: "settings.local.localLyricDirectories.desc", keywords: ["local", "lyric", "folder", "本地", "歌词", "目录"] },
  { category: "local", itemId: "downloadPath", labelKey: "settings.local.downloadPath", descriptionKey: "settings.local.downloadPath.desc", keywords: ["download", "path", "folder", "下载", "目录"] },
  { category: "local", itemId: "downloadMeta", labelKey: "settings.local.downloadMeta", keywords: ["download", "metadata", "tag", "下载", "元数据"] },
  { category: "local", itemId: "downloadCover", labelKey: "settings.local.downloadCover", keywords: ["download", "cover", "art", "下载", "封面"] },
  { category: "local", itemId: "downloadLyric", labelKey: "settings.local.downloadLyric", keywords: ["download", "lyric", "下载", "歌词"] },
  { category: "local", itemId: "downloadLyricTranslation", labelKey: "settings.local.downloadLyricTranslation", keywords: ["download", "translation", "下载", "翻译"] },
  { category: "local", itemId: "downloadThreadCount", labelKey: "settings.local.downloadThreadCount", keywords: ["download", "thread", "concurrent", "下载", "线程"] },
  { category: "local", itemId: "downloadSongLevel", labelKey: "settings.local.downloadSongLevel", keywords: ["download", "quality", "level", "下载", "音质"] },
  { category: "local", itemId: "cacheEnabled", labelKey: "settings.local.cacheEnabled", descriptionKey: "settings.local.cacheEnabled.desc", keywords: ["cache", "缓存"] },
  { category: "local", itemId: "songCacheEnabled", labelKey: "settings.local.songCacheEnabled", keywords: ["cache", "song", "audio", "缓存", "音频"] },
  { category: "local", itemId: "cacheLimit", labelKey: "settings.local.cacheLimit", keywords: ["cache", "limit", "size", "缓存", "上限"] },
  { category: "local", itemId: "clearCache", labelKey: "settings.local.clearCache", descriptionKey: "settings.local.clearCache.desc", keywords: ["cache", "clear", "缓存", "清空", "清除"] },

  // ── keyboard ─────────────────────────────────────────
  { category: "keyboard", itemId: "globalShortcutEnabled", labelKey: "settings.keyboard.globalShortcutEnabled", descriptionKey: "settings.keyboard.globalShortcutEnabled.desc", keywords: ["global", "shortcut", "hotkey", "全局", "快捷键"] },
  { category: "keyboard", itemId: "globalPlayPause", labelKey: "settings.keyboard.action.playPause", keywords: ["global", "play", "pause", "shortcut", "全局", "播放", "暂停"] },
  { category: "keyboard", itemId: "globalNext", labelKey: "settings.keyboard.action.next", keywords: ["global", "next", "shortcut", "全局", "下一首"] },
  { category: "keyboard", itemId: "globalPrev", labelKey: "settings.keyboard.action.prev", keywords: ["global", "previous", "shortcut", "全局", "上一首"] },
  { category: "keyboard", itemId: "globalVolumeUp", labelKey: "settings.keyboard.action.volumeUp", keywords: ["global", "volume", "up", "全局", "音量"] },
  { category: "keyboard", itemId: "globalVolumeDown", labelKey: "settings.keyboard.action.volumeDown", keywords: ["global", "volume", "down", "全局", "音量"] },
  { category: "keyboard", itemId: "localPlayPause", labelKey: "settings.keyboard.action.playPause", keywords: ["page", "play", "pause", "shortcut", "页面", "播放", "暂停"] },
  { category: "keyboard", itemId: "localNext", labelKey: "settings.keyboard.action.next", keywords: ["page", "next", "shortcut", "页面", "下一首"] },
  { category: "keyboard", itemId: "localPrev", labelKey: "settings.keyboard.action.prev", keywords: ["page", "previous", "shortcut", "页面", "上一首"] },
  { category: "keyboard", itemId: "localLike", labelKey: "settings.keyboard.action.like", keywords: ["like", "favorite", "shortcut", "喜欢", "收藏"] },
  { category: "keyboard", itemId: "resetShortcut", labelKey: "settings.keyboard.resetShortcut", descriptionKey: "settings.keyboard.resetShortcut.desc", keywords: ["reset", "default", "shortcut", "恢复", "默认"] },

  // ── network ──────────────────────────────────────────
  { category: "network", itemId: "streamingEnabled", labelKey: "settings.network.streamingEnabled", descriptionKey: "settings.network.streamingEnabled.desc", keywords: ["streaming", "webdav", "subsonic", "流媒体"] },
  { category: "network", itemId: "streamingServerList", labelKey: "settings.network.streamingServerList", descriptionKey: "settings.network.streamingServerList.desc", keywords: ["streaming", "server", "list", "流媒体", "服务器"] },
  { category: "network", itemId: "proxyProtocol", labelKey: "settings.network.proxyProtocol", keywords: ["proxy", "http", "socks5", "代理"] },
  { category: "network", itemId: "proxyServer", labelKey: "settings.network.proxyServer", keywords: ["proxy", "server", "host", "port", "代理", "服务器"] },
  { category: "network", itemId: "proxyTest", labelKey: "settings.network.proxyTest", keywords: ["proxy", "test", "代理", "测试"] },
  { category: "network", itemId: "useRealIP", labelKey: "settings.network.useRealIP", descriptionKey: "settings.network.useRealIP.desc", keywords: ["ip", "region", "unlock", "真实", "解锁"] },
  { category: "network", itemId: "lastfmEnabled", labelKey: "settings.network.lastfmEnabled", keywords: ["lastfm", "last.fm", "scrobble"] },
  { category: "network", itemId: "lastfmConnect", labelKey: "settings.network.lastfmConnect", keywords: ["lastfm", "connect", "login", "连接"] },
  { category: "network", itemId: "lastfmScrobble", labelKey: "settings.network.lastfmScrobble", keywords: ["lastfm", "scrobble", "记录"] },
  { category: "network", itemId: "lastfmNowplaying", labelKey: "settings.network.lastfmNowplaying", keywords: ["lastfm", "now", "playing", "正在播放"] },
  { category: "network", itemId: "discordEnabled", labelKey: "settings.network.discordEnabled", descriptionKey: "settings.network.discordEnabled.desc", keywords: ["discord", "rpc", "rich presence"] },
  { category: "network", itemId: "discordPaused", labelKey: "settings.network.discordPaused", keywords: ["discord", "paused", "暂停"] },
  { category: "network", itemId: "socketEnabled", labelKey: "settings.network.socketEnabled", descriptionKey: "settings.network.socketEnabled.desc", keywords: ["websocket", "socket", "amll", "ws"] },
  { category: "network", itemId: "socketTest", labelKey: "settings.network.socketTest", keywords: ["websocket", "test", "测试"] },
  { category: "network", itemId: "smtcOpen", labelKey: "settings.network.smtcOpen", descriptionKey: "settings.network.smtcOpen.desc", keywords: ["smtc", "windows", "media", "控件", "媒体"] },

  // ── about ────────────────────────────────────────────
  { category: "about", itemId: "appVersion", labelKey: "settings.nav.about", descriptionKey: "settings.about.appVersion.desc", keywords: ["version", "lyne", "about", "版本", "关于"] },
  { category: "about", itemId: "checkUpdate", labelKey: "settings.about.checkUpdate", descriptionKey: "settings.about.checkUpdate.desc", keywords: ["update", "check", "更新", "检查"] },
  { category: "about", itemId: "changelog", labelKey: "settings.about.changelog", keywords: ["changelog", "release", "notes", "更新日志"] },
  { category: "about", itemId: "projectRepo", labelKey: "settings.about.projectRepo", keywords: ["project", "repo", "github", "source", "项目", "仓库"] },
  { category: "about", itemId: "reportIssue", labelKey: "settings.about.reportIssue", keywords: ["issue", "bug", "feedback", "反馈", "问题"] },
  { category: "about", itemId: "contributors", labelKey: "settings.about.contributors", keywords: ["contributors", "credits", "贡献", "致谢"] },
  { category: "about", itemId: "references", labelKey: "settings.about.references", descriptionKey: "settings.about.references.desc", keywords: ["reference", "inspire", "credits", "参考", "鸣谢"] }
];
